version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk_network

    logstash:
      image: docker.elastic.co/logstash/logstash:8.17.0
      container_name: logstash
      user: root
      command: >
        bash -c "
          export DEBIAN_FRONTEND=noninteractive &&
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime &&
          apt-get update &&
          apt-get install -y tzdata awscli &&
          dpkg-reconfigure --frontend noninteractive tzdata &&
          bin/logstash-plugin install logstash-filter-grok &&
        
          bin/logstash-plugin install logstash-filter-useragent &&
          bin/logstash-plugin install logstash-patterns-core &&
          bin/logstash"
      volumes:
        - ./logstash/pipeline:/usr/share/logstash/pipeline
        - ./logstash/config:/usr/share/logstash/config
        - ./sincedb:/var/lib/logstash/sincedb
        - ~/.aws:/root/.aws
      environment:
        - TZ=Asia/Kolkata
        - XPACK_MONITORING_ENABLED=false
        - AWS_PROFILE=default
        - AWS_DEFAULT_REGION=us-east-1
      depends_on:
        - elasticsearch
      networks:
        - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - elk_network

volumes:
  esdata:
    driver: local

networks:
  elk_network:
    driver: bridge