version: '3.8'

services:
  loki:
    image: grafana/loki:3.2.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
      - loki-data:/loki
    command: -config.file=/mnt/config/loki-config.yaml

  promtail:
    image: grafana/promtail:3.2.1
    volumes:
      - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
      - ./logs:/var/log
    depends_on:
      - loki
    command: -config.file=/mnt/config/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - loki

volumes:
  loki-data:
  grafana-data: