http.host: 0.0.0.0
log.level: debug
node.name: logstash-s3-alb-log-processor
path.logs: /usr/share/logstash/logs
pipeline.workers: 2
queue.type: persisted
xpack.monitoring.enabled: ${XPACK_MONITORING_ENABLED}
