http.host: 0.0.0.0
log.level: info
monitoring.enabled: false
node.name: logstash-s3-alb-log-processor
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs
pipeline.batch.delay: 50
pipeline.batch.size: 125
pipeline.workers: 2
queue.max_bytes: 1gb
queue.type: persisted
xpack.monitoring.enabled: false
